version: '3.8'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0 -p 4000
    container_name: products-app
    ports:
      - 4000:4000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
    - products-app_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
volumes:
  products-app_data: